Converter logic
EDGENortheastern/olaniyioshinusi-systems-testing pull request #7
Opened 2022-09-28 13:42 UTC by OlaniyiOshinusi

2022-09-29 09:40 UTC, jcsaenzcarrasco requested changes
You need to delete code that is no longer functional

2022-09-29 09:40 UTC, jcsaenzcarrasco commented on src/helper.js
> +const convertToNum = (val) => parseInt(val);
I don't think you now have the function convertToNum, you should not test it

2022-09-29 09:40 UTC, jcsaenzcarrasco commented on src/App.test.js
>    const celsiusInput = screen.getByRole('textbox');//Gets the input box and assigns it to a variable
```suggestion

```

2022-10-03 15:14 UTC, alexcasper approved these changes
Seems ok to me!

2022-10-03 15:18 UTC, missKatiaPunter approved these changes

2022-10-03 15:18 UTC, jcsaenzcarrasco approved these changes

2022-10-03 15:19 UTC, merged